[package]
name = "quoddel"
version = "0.1.0-alpha"
edition = "2021"

[dependencies]
clap = "3"
seq_io = "0.3"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"

[profile.release]
lto = true